name: Tests
on:
  push:
    branches:
      - master
      - v4
  pull_request:
    branches:
      - master
      - v4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install deps
        run: npm ci
      - name: Test
        run: npm test
      - name: Performance
        run: npm performance
